// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJHzLmEBHeMnfZh0jQJ8NzzwVzYBZOlhw',
    appId: '1:255313947969:web:8556c20be54b4cb4be05c0',
    messagingSenderId: '255313947969',
    projectId: 'corider-b3661',
    authDomain: 'corider-b3661.firebaseapp.com',
    storageBucket: 'corider-b3661.appspot.com',
    measurementId: 'G-NZ2VR64G1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF0tuH6N0JDQRAgc9JMIpHfFxDevYC_vk',
    appId: '1:255313947969:android:71d52551bb956274be05c0',
    messagingSenderId: '255313947969',
    projectId: 'corider-b3661',
    storageBucket: 'corider-b3661.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWgIGTHRgiEWlImV7-zfTo-IUq4RzWMzg',
    appId: '1:255313947969:ios:a3ef6eaa00f0fbe4be05c0',
    messagingSenderId: '255313947969',
    projectId: 'corider-b3661',
    storageBucket: 'corider-b3661.appspot.com',
    iosBundleId: 'com.example.corider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWgIGTHRgiEWlImV7-zfTo-IUq4RzWMzg',
    appId: '1:255313947969:ios:7624a3c480753e99be05c0',
    messagingSenderId: '255313947969',
    projectId: 'corider-b3661',
    storageBucket: 'corider-b3661.appspot.com',
    iosBundleId: 'com.example.corider.RunnerTests',
  );
}
