name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
    setup-env:
      runs-on: self-hosted
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Install Flutter
          uses: subosito/flutter-action@v2
        - run: flutter --version
        - name: Install dependencies
          run: flutter pub get

    basic-analysis:
      # Basic analysis
      needs: setup-env
      runs-on: self-hosted

      steps:
        - name: Run tests
          run: flutter test
        - name: Analyze
          run: flutter analyze --no-fatal-infos --no-fatal-warnings

    build-android:
      # Build Android APK and app bundle
      needs: basic-analysis
      runs-on: self-hosted

      steps:
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            distribution: 'zulu'
            java-version: '11'
        - name: Build release APK
          run: flutter build apk --release
        - name: Build release app bundle
          run: flutter build appbundle
        # - name: Delete previous APK artifact
        #   uses: geekyeggo/delete-artifact@v2
        #   with:
        #     name: CoRider.apk
        # - name: Upload APK
        #   uses: actions/upload-artifact@v3
        #   with:
        #     name: CoRider.apk
        #     path: build/app/outputs/apk/release/app-release.apk

    build-ios:
      # Build for iOS
      needs: basic-analysis
      runs-on: self-hosted
      steps:
        - name: Build release iOS app
          run: flutter build ios --release --no-codesign
        # - name: Delete previous iOS app artifact
        #   uses: geekyeggo/delete-artifact@v2
        #   with:
        #     name: CoRider.app
        # - name: Upload iOS app
        #   uses: actions/upload-artifact@v3
        #   with:
        #     name: CoRider.app
        #     path: build/ios/iphoneos/Runner.app