name: Flutter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
    build-android:
      # # Basic analysis & Build Android APK and app bundle
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - uses: subosito/flutter-action@v2
        - uses: actions/setup-java@v2
          with:
            distribution: 'zulu'
            java-version: '11'
        - run: flutter pub get
        - name: Run test
          run: flutter test
        - name: flutter analyze
          run: flutter analyze --no-fatal-infos --no-fatal-warnings
        - run: flutter build apk
        - run: flutter build appbundle

    build-ios:
      # Build for iOS
      runs-on: macos-latest

      steps:
        - uses: actions/checkout@v3
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
            architecture: x64
        - run: flutter pub get
        - run: flutter build ios --release --no-codesign